# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:25
from __future__ import unicode_literals

import course_system.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=42)),
                ('courseID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('about', models.CharField(max_length=999)),
                ('provided_by_institute', models.CharField(blank=True, default='freelance', max_length=99)),
                ('domain', models.CharField(max_length=33)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('partID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content_location', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('content_name', models.CharField(max_length=30)),
                ('content_type', models.CharField(max_length=18)),
                ('has_evaluation', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('website', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('instructorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('courses', models.ManyToManyField(to='course_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('nick', models.CharField(max_length=12, unique=True)),
                ('website', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(max_length=69, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('status', models.CharField(blank=True, default='audit', max_length=9, validators=[course_system.models.validate_status])),
                ('performance', models.FloatField(blank=True, default=0, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_system.Learners')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('score', models.IntegerField(default=0, validators=[course_system.models.validate_marks])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_system.Learners')),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_system.CourseContent')),
            ],
        ),
        migrations.AddField(
            model_name='learners',
            name='courses',
            field=models.ManyToManyField(to='course_system.Course'),
        ),
    ]
