# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 09:08
from __future__ import unicode_literals

import courseSystem.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(max_length=69, primary_key=True, serialize=False, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=42)),
                ('courseID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('about', models.CharField(max_length=999)),
                ('provided_by_institute', models.CharField(blank=True, default='freelance', max_length=99)),
                ('domain', models.CharField(max_length=33)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('partID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content_location', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('content_name', models.CharField(max_length=30)),
                ('content_type', models.CharField(max_length=18)),
                ('has_evaluation', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseSystem.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('courses', models.ManyToManyField(blank=True, to='courseSystem.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('status', models.CharField(blank=True, default='audit', max_length=9, validators=[courseSystem.models.validate_status])),
                ('performance', models.FloatField(blank=True, default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courseSystem.Learners', unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseSystem.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('score', models.IntegerField(default=0, validators=[courseSystem.models.validate_marks])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courseSystem.Learners', unique=True)),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseSystem.CourseContent')),
            ],
        ),
        migrations.AddField(
            model_name='learners',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courseSystem.Course'),
        ),
        migrations.AddField(
            model_name='learners',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
