# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSystem', '0002_auto_20160306_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
