# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSystem', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_module_perms',
            field=models.BooleanField(default=True),
        ),
    ]
