# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseSystem', '0004_myuser_has_module_perms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='has_module_perms',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
